---
- name: install firefox
  pacman:
    name: firefox
    state: present
- name: install pip
  pacman:
    name: python-pip
    state: present
  become: yes
- name: install python reqeust for firefox addon role
  pip:
    name: requests
    state: present
- name: run addon installation
  include_role:
    name: basvandenbrink.firefox
