---
- name: install firefox\
  pacman:
    name: firefox
    state: present
# - name: install firefox addon-dependencies
#   block:
#     - pacman:
#         name: sed
#         state: present
#     - pacman:
#         name: libxml2
#         state: present
#     - pacman:
#         name: unzip
#         state: present
#     - pacman:
#         name: curl
#         state: present
# - name: install bitwarden
#   firefox_addon:
#     url: https://addons.mozilla.org/id/firefox/addon/bitwarden-password-manager
#     state: present
