---
- hosts: localhost
  connection: local

  roles:
    - kewlfft.aur

  tasks:
    - name: Install yay
      aur:
        name: yay
        state: present
    - name: Install apps
      pacman:
        name:
          - vim
          - nano
