---
- hosts: localhost
  connection: local
  become: yes

  roles:
    - kewlfft.aur

  tasks:
    - name: Install yay
      aur:
        name: yay
        state: present
    - name: Install vim
      pacman:
        name: vim
        state: present
    - name: install curl
      pacman:
        name: curl
        state: present
    - name: install nano
      pacman:
        name: nano
        state: present
    - name: install firefox
      pacman:
        name: firefox
        state: present
    - name: install calibre
      pacman:
        name: calibre
        state: present
    # - name: add spotify gpg not working currently
    #   shell: "curl -sS https://download.spotify.com/debian/pubkey_0D811D58.gpg | gpg --import -"
    - name: install spotify
      aur:
        name: spotify
        state: present
      become: no
    - name: install vscode
      aur:
        name: visual-studio-code-bin
        state: present
      become: no
    - name: install postman
      aur:
        name: postman-bin
        state: present
      become: no
    - name: install google chrome
      aur:
        name: google-chrome
        state: present
      become: no
    - name: install steam
      pacman:
        name: steam
        state: present
    - name: install vlc
      pacman:
        name: vlc
        state: present
    - name: install gnome-terminal-transparency
      aur:
        name: gnome-terminal-transparency
        state: present
      become: no
