---
- hosts: localhost
  connection: local
  become: yes

  tasks:
    - name: install gnome and gnome-extra
      pacman:
        name:
          - gnome
          - gnome-extra
        state: present
