---
- hosts: localhost
  connection: local
  become: yes

  tasks:
    - name: install gnome and gnome-extra
      pacman:
        name:
          - gnome
          - gnome-extra
        state: present
        extra_args: --noconfirm
        update_cache: yes
    - name: enable gdm
      service:
        name: gdm
        enabled: yes
        state: started
