# need to run as root only no process for user should be allowed
---
- hosts: localhost
  connection: local

  vars_prompt:
    - name: username
      prompt: What is your username?
      private: no
    - name: password
      prompt: What is your password?

  tasks:
    - name: install encryptfs and it's dependencies
      pacman:
        name:
          - rsync
          - lsof
          - ecryptfs-utils
          - python-pexpect
        state: present
    - name: load module ecryptfs
      command: "modprobe ecryptfs"
    - name: Check if folder already encrypted by ecryptfs
      stat: "path=/home/.ecryptfs/{{ username }}"
      register: encryptdir
    - name: encrypt home for user
      expect:
        command: "ecryptfs-migrate-home -u {{ username }}"
        responses:
          (?i)passphrase: "{{ password }}"
      when: not encryptdir.stat.exists
    - name: add automount encrypted folder
      block:
        - pamd:
            name: system-auth
            type: auth
            control: "[default=die]"
            module_path: pam_faillock.so
            new_type: auth
            new_control: "[success=1 default=ignore]"
            new_module_path: pam_succeed_if.so
            state: after
            module_arguments: "service = systemd-user quiet"
        - pamd:
            name: system-auth
            type: auth
            control: "[success=1 default=ignore]"
            module_path: pam_succeed_if.so
            new_type: auth
            new_control: required
            new_module_path: pam_ecryptfs.so
            state: after
            module_arguments: unwrap
        - pamd:
            name: system-auth
            type: password
            control: required
            module_path: pam_unix.so
            new_type: password
            new_control: optional
            new_module_path: pam_ecryptfs.so
            state: before
        - pamd:
            name: system-auth
            type: session
            control: required
            module_path: pam_unix.so
            new_type: session
            new_control: "[success=1 default=ignore]"
            new_module_path: pam_succeed_if.so
            state: after
            module_arguments: "service = systemd-user quiet"
        - pamd:
            name: system-auth
            type: session
            control: "[success=1 default=ignore]"
            module_path: pam_succeed_if.so
            new_type: session
            new_control: optional
            new_module_path: pam_ecryptfs.so
            state: after
